config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :todo_lists do
    resources :todo_items
  end
  
  # get "home/index"
  # root 'home#index'
  root 'todo_lists#index'

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list

  before_save :set_completed_at, if: :completed_changed?

  scope :completed, -> do
    where(completed: true)
  end

  def set_completed_at
    if completed
      self.completed_at = Time.current
    else
      self.completed_at = nil
    end
  end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  has_many :todo_items
  belongs_to :user

  def percent_completed
    return 0 if total_items == 0
    @percent_completed = (100 * completed_items.to_f / total_items).round(1)
  end

  def completed_items
    @completed_items ||= todo_items.completed.count
  end

  def total_items
    @total_items ||= todo_items.count
  end

  def status
    case percent_completed.to_i
    when 0
      "Not started"
    when 100
      "Completed"
    else
      "In progress"
    end
  end

  def status_color
    case percent_completed.to_i
    when 0
      "dark"
    when 100
      "info"
    else
      "primary"
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :todo_list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list
  before_action :set_todo_item, only: [:show, :edit, :update, :destroy]

  # GET todo_lists/1/todo_items
  def index
    @todo_items = @todo_list.todo_items
  end

  # GET todo_lists/1/todo_items/1
  def show
  end

  # GET todo_lists/1/todo_items/new
  def new
    @todo_item = @todo_list.todo_items.build
  end

  # GET todo_lists/1/todo_items/1/edit
  def edit
  end

  # POST todo_lists/1/todo_items
  def create
    @todo_item = @todo_list.todo_items.build(todo_item_params)

    if @todo_item.save
      redirect_to(@todo_item.todo_list)
    else
      render action: 'new'
    end
  end

  # PUT todo_lists/1/todo_items/1
  def update
    if @todo_item.update(todo_item_params)
      redirect_to([@todo_item.todo_list, @todo_item], notice: 'Todo item was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE todo_lists/1/todo_items/1
  def destroy
    @todo_item.destroy

    redirect_to todo_list_todo_items_url(@todo_list)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:todo_list_id])
    end

    def set_todo_item
      @todo_item = @todo_list.todo_items.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def todo_item_params
      params.require(:todo_item).permit(:description, :completed, :completed_at, :todo_list_id)
    end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: %i[ edit update destroy ]
  before_action :redirect_if_not_signed_in, only: [:index]

  # GET /todo_lists or /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1 or /todo_lists/1.json
  def show
    @todo_item = TodoItem.new
  end

  # GET /todo_lists/new
  def new
    # @todo_list = TodoList.new
    @todo_list = current_user.todo_list.build
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists or /todo_lists.json
  def create
    # @todo_list = TodoList.new(todo_list_params)
    @todo_list = current_user.todo_list.build(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: "Todo list was successfully created." }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1 or /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: "Todo list was successfully updated." }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1 or /todo_lists/1.json
  def destroy
    @todo_list.destroy!

    respond_to do |format|
      format.html { redirect_to todo_lists_path, status: :see_other, notice: "Todo list was successfully deleted." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @todo_list = current_user.todo_list.find_by(id: params[:id])
    redirect_to todo_lists_path, notice: "Not Authorized To Edit This Todo List" if @todo_list.nil?
  end

  def redirect_if_not_signed_in
    redirect_to new_user_session_path unless user_signed_in?
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def todo_list_params
      params.expect(todo_list: [ :title, :user_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark d-flex align-items-center">
  <div class="container-fluid">

    <%= link_to 'Todo List App', root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <% if user_signed_in? %>

          <li class="nav-item">
            <%= link_to 'Add Todo List', new_todo_list_path, class:"nav-link" %>
          </li>

          <%= form_with url: destroy_user_session_path, method: :delete, local: true do %>
            <button type="submit" class="nav-link">Sign Out</button>
          <% end %>

          <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
          </li>

        <% else %>

          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
          </li>
          
          <li class="nav-item">
            <%= link_to 'Sign In', user_session_path, class:"nav-link" %>
          </li>

        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Hello World!!!</h1>

This is my second rails project

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close">
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">

    <title><%= content_for(:title) || "Rails Todo List" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="bg-light">

    <%= render 'home/header' %>

    <div class="container">
      <div class="row">
        <div class="col-md-10 col-lg-8 offset-md-1 offset-lg-2">
          
          <% if notice %>
            <%= render 'layouts/alerts' %>
          <% end %>

          <div class="card mt-5">
            <%= yield %>
          </div>
        </div>
      </div>
      <br/>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for([@todo_item.todo_list, @todo_item]) do |f| %>
  <% if @todo_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h2>

      <ul>
      <% @todo_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group mb-2">
    <%= f.label :description %><br />
    <%= f.textarea :description, class:"form-control" %>
  </div>
  <div class="field form-group mb-2">
    <%= f.label :completed %><br />
    <%= f.checkbox :completed, class:"form-check-input" %>
  </div>

  <div class="actions mt-1">
    <%= f.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/todo_items/edit.html.erb
<% content_for :title, "Editing todo item" %>

<div class="card-header d-flex justify-content-left">
  <div class="d-flex gap-4 align-items-center">
    <div>
      <%= link_to todo_list_todo_items_path(@todo_item.todo_list), class:"btn btn-dark" do %>
        <i class="fas fa-angle-left"></i>
      <% end %>
    </div>
    <div> 
      <h5 class="m-0">
        <b>Edit Todo Item</b>
      </h5>
    </div> 
  </div>
</div>

<div class="card-body">
  <%= render 'form' %>

  <div class="d-flex mt-5">
    <%= link_to 'Delete this Todo Item', [@todo_item.todo_list, @todo_item], method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  </div>
</div>

app/views/todo_items/index.html.erb
<div class="card-header d-flex justify-content-between">
  <div>
    <div class="d-flex gap-4 align-items-center">
      <div>
        <%= link_to todo_list_path(@todo_list), class:"btn btn-dark" do %>
          <i class="fas fa-angle-left"></i>
        <% end %>
      </div>
      <div> 
        <h5 class="m-0">
          <b><%= @todo_list.title %></b>
          <span class="badge text-bg-<%= @todo_list.status_color %> rounded-pill">
            <%= @todo_list.status %>
          </span>
        </h5>
        <p class="text-secondary m-0"><small><%= @todo_list.percent_completed %>% Completed (<%= @todo_list.completed_items %>/<%= @todo_list.total_items %> Todo Items)</small></p>
      </div> 
    </div>
  </div>
</div>
<div class="card-body">

  <table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Description</th>
        <th>Completed</th>
        <th>Completed at</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @todo_items.each do |todo_item| %>
        <tr>
          <td><%= link_to todo_item.description, [todo_item.todo_list, todo_item] %></td>
          <td><%= todo_item.completed %></td>
          <td><%= todo_item.completed_at %></td>
          <td><%= link_to 'Edit', edit_todo_list_todo_item_path(todo_item.todo_list, todo_item), class:"btn btn-warning btn-sm" %></td>
          <td>
            <%= link_to 'Destroy', [todo_item.todo_list, todo_item], method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class:"btn btn-danger btn-sm" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br />

  <%= link_to 'New Todo Item', new_todo_list_todo_item_path(params[:todo_list_id]), class:"btn btn-primary" %>
</div>

app/views/todo_items/new.html.erb
<div class="card-header d-flex justify-content-left">
  <div class="d-flex gap-4 align-items-center">
    <div>
      <%= link_to todo_list_todo_items_path(@todo_item.todo_list), class:"btn btn-dark" do %>
        <i class="fas fa-angle-left"></i>
      <% end %>
    </div>
    <div> 
      <h5 class="m-0">
        <b>New Todo Item</b>
      </h5>
    </div> 
  </div>
</div>

<div class="card-body">
  <%= render 'form' %>
</div>

app/views/todo_items/show.html.erb
<% content_for :title, "Todo item" %>

<div class="card-header d-flex justify-content-left">
  <div class="d-flex gap-4 align-items-center">
    <div>
      <%= link_to todo_list_todo_items_path(@todo_item.todo_list), class:"btn btn-dark" do %>
        <i class="fas fa-angle-left"></i>
      <% end %>
    </div>
    <div> 
      <h5 class="m-0">
        <b><%= @todo_item.description %> </b>
      </h5>
    </div> 
  </div>
</div>

<div class="card-body">
  <p>
    <b>Completed:</b>
    <%= @todo_item.completed %>
  </p>

  <p>
    <b>Completed at:</b>
    <%= @todo_item.completed_at %>
  </p>

  <div class="d-flex mt-5">
    <%= link_to 'Delete this Todo Item', [@todo_item.todo_list, @todo_item], method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  </div>
</div>

app/views/todo_lists/_form.html.erb
<%= form_with(model: todo_list) do |form| %>
  <% if todo_list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
        <% todo_list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-2">
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class:"form-control", placeholder:"Todo title" %>
  </div>

  <div class="form-group mb-2">
    <%= form.number_field :user_id, id: :todo_list_user_id, class:"form-control", value: current_user.id, type: :hidden %>
  </div>

  <div class="mt-2">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/todo_lists/_todo_list.html.erb
<div id="<%= dom_id todo_list %>">
  <p>
    <strong>Title:</strong>
    <%= todo_list.title %>
  </p>

</div>

app/views/todo_lists/edit.html.erb
<% content_for :title, "Editing todo list" %>

<div class="card-header d-flex justify-content-left">
  <div class="d-flex gap-4 align-items-center">
    <div>
      <%= link_to todo_lists_path, class:"btn btn-dark" do %>
        <i class="fas fa-angle-left"></i>
      <% end %>
    </div>
    <div> 
      <h5 class="m-0">
        <b>Edit Todo List</b>
      </h5>
    </div> 
  </div>
</div>

<div class="card-body">
  <%= render "form", todo_list: @todo_list %>

  <div class="d-flex mt-5">
    <%= link_to 'Delete this Todo List', @todo_list, method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  </div>
</div>

app/views/todo_lists/index.html.erb
<% content_for :title, "Todo Lists" %>

<div class="card-header d-flex justify-content-between">
  <h5 class="m-0 text-dark">
    Todo Lists
  </h5>
  <%= link_to "New todo list", new_todo_list_path, class:"btn btn-primary btn-sm" %>  
</div>

<div class="card-body">
  <ul class="list-group">
    <% @todo_lists.each do |todo_list| %>
      <% if todo_list.user == current_user %>
        <%= link_to todo_list, class:"text-decoration-none" do %>
          <li class="list-group-item d-flex justify-content-between todo-item-hover">
            <div>
              <h6 class="m-0 text-dark">
                <b><%= todo_list.title %></b>
                <span class="badge text-bg-<%= todo_list.status_color %> rounded-pill">
                  <%= todo_list.status %>
                </span>
              </h6>
              <p class="text-secondary m-0"><small><%= todo_list.percent_completed %>% Completed (<%= todo_list.completed_items %>/<%= todo_list.total_items %> Todo Items)</small></p>
            </div>

            <div class="d-flex align-items-center gap-3">
              <%= link_to "Edit",  edit_todo_list_path(todo_list), class:"btn btn-warning" %>  
              <%= link_to 'Delete', todo_list, method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "btn btn-danger" %>
            </div>
          </li>
        <% end %>
      <% end %>
    <% end %>
  </ul>
</div>

<style>
  .todo-item-hover:hover {
    background-color: #f8f9fa;
    cursor: pointer;
  }
</style>

app/views/todo_lists/new.html.erb
<% content_for :title, "Add New Todo List" %>

<div class="card-header d-flex justify-content-left">
  <div class="d-flex gap-4 align-items-center">
    <div>
      <%= link_to todo_lists_path, class:"btn btn-dark" do %>
        <i class="fas fa-angle-left"></i>
      <% end %>
    </div>
    <div> 
      <h5 class="m-0">
        <b>Add New Todo List</b>
      </h5>
    </div> 
  </div>
</div>

<div class="card-body">
  <%= render "form", todo_list: @todo_list %>
</div>

app/views/todo_lists/show.html.erb
<% content_for :title, @todo_list.title %>

<div class="card-header d-flex justify-content-between">
  <div>
    <div class="d-flex gap-4 align-items-center">
      <div>
        <%= link_to todo_lists_path, class:"btn btn-dark" do %>
          <i class="fas fa-angle-left"></i>
        <% end %>
      </div>
      <div> 
        <h5 class="m-0">
          <b><%= @todo_list.title %></b>
          <span class="badge text-bg-<%= @todo_list.status_color %> rounded-pill">
            <%= @todo_list.status %>
          </span>
        </h5>
        <p class="text-secondary m-0"><small><%= @todo_list.percent_completed %>% Completed (<%= @todo_list.completed_items %>/<%= @todo_list.total_items %> Todo Items)</small></p>
      </div> 
    </div>
  </div>

  <div class="d-flex gap-2 align-items-center">
    <%= link_to "Edit",  edit_todo_list_path(@todo_list), class:"btn btn-secondary" %>  
    <%= link_to todo_list_todo_items_path(@todo_list), class: "btn btn-outline-primary d-flex align-items-center gap-2" do %>
      <span>See More Details</span>
      <i class="fas fa-arrow-right"></i>
    <% end %>
  </div>
</div>

<div class="card-body">
  <div class="progress mb-4">
    <div class="progress-bar bg-info" role="progressbar" style="width: <%= @todo_list.percent_completed %>%" aria-valuenow="<%= @todo_list.percent_completed %>" aria-valuemin="0" aria-valuemax="100"></div>
  </div>

  <%= form_for([@todo_list, @todo_item]) do |f| %>
    <div class="input-group mb-4"> 
      <%= f.text_field :description, class:"form-control", placeholder:"Add a todo item" %>
      <div class="input-group-append">
        <%= f.submit "Add", class:"btn btn-primary input-group-btn" %>
      </div>
    </div>
  <% end %>

  <ul class="list-group">
    <% @todo_list.todo_items.each do |todo_item| %>
      <% if todo_item.completed? %>
        <li class="list-group-item bg-light">
          <div class="d-flex justify-content-between">
            <span class="text-muted">
              <em><%= todo_item.description %></em>
            </span>
            
            <div>
              <%= link_to "#", class:"btn btn-dark btn-sm", data: {reflex: 'click->TodoItem#mark_incomplete', id: todo_item.id} do %>
                <i class="fas fa-undo-alt"></i>
              <% end %>

              <%= link_to edit_todo_list_todo_item_path(todo_item.todo_list, todo_item), class:"btn btn-warning btn-sm" do %>
                <i class="fas fa-edit"></i>
              <% end %>

              <%= link_to [todo_item.todo_list, todo_item], method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class:"btn btn-danger btn-sm" do %>
                <i class="fas fa-trash"></i>
              <% end %>
            </div>
            
          </div>
        </li>
      <% else %>
        <li class="list-group-item">
          <div class="d-flex justify-content-between">
            <span>
              <%= todo_item.description %>
            </span>
            
            <div>
              <%= link_to "#", class:"btn btn-info btn-sm", data: {reflex: 'click->TodoItem#mark_complete', id: todo_item.id} do %>
                <i class="fas fa-check"></i>
              <% end %>

              <%= link_to edit_todo_list_todo_item_path(todo_item.todo_list, todo_item), class:"btn btn-warning btn-sm" do %>
                <i class="fas fa-edit"></i>
              <% end %>

              <%= link_to [todo_item.todo_list, todo_item], method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class:"btn btn-danger btn-sm" do %>
                <i class="fas fa-trash"></i>
              <% end %>
            </div>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>